---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.6

inputs:
  - name: dp-frontend-interactives-controller

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-frontend-interactives-controller/ci/scripts/build.sh
